include: package:flutter_lints/flutter.yaml

linter:
  rules:
    require_trailing_commas: true
    always_declare_return_types: true
    always_use_package_imports: true
    prefer_const_constructors: false
    prefer_single_quotes: true
    cancel_subscriptions: true
    annotate_overrides: true
    empty_constructor_bodies: true